# Generated by Django 4.2 on 2024-08-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('clave', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=60)),
            ],
        ),
    ]
